name: CI +PraTi Hub

on:
  push:
    branches:
      - main
      - develop
      - ci-cd
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      # desativa o Ryuk (container de limpeza) do Testcontainers para evitar problemas no CI
      TESTCONTAINERS_RYUK_DISABLED: "true"
      # ativa logging detalhado do Testcontainers
      TESTCONTAINERS_LOGGING: "DEBUG"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      # imagem para testes
      - name: Pull MongoDB image
        run: docker pull mongo:7.0.5

      - name: Build with Maven
        run: mvn clean install -B

      - name: Run tests (unit + integration)
        run: mvn verify -B
